trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Instalar Node.js'

  - script: npm install
    displayName: 'Instalar dependências'

  - script: |
      npx cypress run --spec "cypress/e2e/**/*.cy.js"\
      --reporter cypress-mochawesome-reporter \
      --reporter-options "reportDir=cypress/reports/html,overwrite=false,html=true,json=true"
    displayName: 'Executar testes Cypress'

  - script: |
      npx mochawesome-merge cypress/reports/html/*.json -o cypress/reports/html/report.json
      npx marge cypress/reports/html/report.json -f report --reportDir cypress/reports/html
    displayName: 'Gerar relatório HTML a partir dos JSONs'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'cypress/reports/html'
      artifact: 'relatorio-cypress'
      publishLocation: 'pipeline'
    displayName: 'Publicar relatório como artefato'