trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Instalar Node.js'

  - script: npm install
    displayName: 'Instalar dependências'

  - script: |
      export TERM=xterm
      npx cypress run --spec "cypress/e2e/**" \
        --config video=false \
        --reporter mocha-junit-reporter \
        --reporter-options mochaFile=cypress/reports/results.xml
    displayName: 'Executar testes Cypress'   

  - script: |
      npx mochawesome-merge cypress/reports/html/*.json > mochawesome.json
      npx marge mochawesome.json --reportDir cypress/reports/html --reportFilename index.html
    displayName: 'Gerar relatório'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/cypress/reports/*.xml'
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'cypress/screenshots'
      ArtifactName: 'ScreenshotsCypress'
      publishLocation: 'Container'
    condition: succeededOrFailed()
    continueOnError: true