trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Instalar Node.js'

  - script: npm install
    displayName: 'Instalar dependências'

  - script: npx cypress run --spec "cypress/e2e/**"
    displayName: 'Executar testes Cypress'