trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Instalar Node.js'

  - script: npm install
    displayName: 'Instalar dependências'

  - script: mkdir -p cypress/reports/html
    displayName: 'Criar diretório de relatórios'
  
  - script: |
      npx cypress run \
        --spec "cypress/e2e/**/*.cy.js" --config-file cypress.config.js
    displayName: 'Executar testes Cypress'

  - script: |
      ls -lR cypress/reports/html
    displayName: 'Verificar arquivos gerados pelo Cypress'    

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'cypress/reports/html'
      artifact: 'relatorio-cypress'
      publishLocation: 'pipeline'
    displayName: 'Publicar relatório como artefato'