trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Instalar Node.js'

  - script: npm install
    displayName: 'Instalar dependências'

  - script: npx cypress run --spec "cypress/e2e/**" --config video=false --reporter mocha-junit-reporter --reporter-options mochaFile=cypress/reports/results.xml
    displayName: 'Executar testes Cypress'

  - script: |
      npx mochawesome-merge cypress/reports/*.json > cypress/reports/output.json
      npx mochawesome-report-generator cypress/reports/output.json --reportDir cypress/reports --inline
    displayName: 'Gerar relatório HTML'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/cypress/reports/*.xml'
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'cypress/reports'
      ArtifactName: 'RelatorioCypress'
      publishLocation: 'Container'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'cypress/screenshots'
      ArtifactName: 'ScreenshotsCypress'
      publishLocation: 'Container'
    condition: succeededOrFailed()
    continueOnError: true