trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Instalar Node.js'

  - script: npm install
    displayName: 'Instalar dependências'

  - script: |
      npx cypress run --spec "cypress/e2e/**" \
        --config video=false \
        --reporter mocha-junit-reporter \
        --reporter-options mochaFile=cypress/reports/results.xml
    displayName: 'Executar testes Cypress'

  - script: |
      npx mochawesome-merge cypress/reports/*.json > cypress/reports/output.json
      npx mochawesome-report-generator cypress/reports/output.json --reportDir cypress/reports --inline
    displayName: 'Gerar relatório HTML (Mochawesome)'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'cypress/reports/results.xml'
    condition: succeededOrFailed()
    displayName: 'Publicar resultado JUnit no Azure'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'cypress/reports'
      ArtifactName: 'RelatorioCypress'
      publishLocation: 'Container'
    displayName: 'Publicar relatório HTML como artefato'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'cypress/screenshots'
      ArtifactName: 'ScreenshotsCypress'
      publishLocation: 'Container'
    condition: succeededOrFailed()
    continueOnError: true
    displayName: 'Publicar screenshots de falhas'